development:
  adapter: postgresql
  database: ming_strikingly_dev
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ming_strikingly_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: ming_strikingly_prod
  pool: 5
  username: myapp
  password: